targets:
  $default:
    sources:
      - "lib/**"
      - "!lib/**/*~"        # vim backup files
      - "!lib/**/.*"        # hidden files
      - "!lib/**/*.swp"     # vim swap files
      - "!lib/**/*.swo"     # vim swap files
      - "!lib/**/*.swn"     # vim swap files
      - "!lib/**/[0-9]*"    # numeric temp files
      - "!lib/**/#*"        # emacs temp files
