// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIWBrMuaqPr67fpVqS3iVwaHlGwDvMKs',
    appId: '1:337862523976:web:7b5e6795a4c50778d4ec7d',
    messagingSenderId: '337862523976',
    projectId: 'mush-on',
    authDomain: 'mush-on.firebaseapp.com',
    storageBucket: 'mush-on.firebasestorage.app',
    measurementId: 'G-3TNMY53NMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4eTNzos2L1sC4aDJdJpQpBtk4eeWMeo',
    appId: '1:337862523976:android:879d6deefe9a6172d4ec7d',
    messagingSenderId: '337862523976',
    projectId: 'mush-on',
    storageBucket: 'mush-on.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9T5oaPLO53_C5wS1axF611sFkb8YQ9QQ',
    appId: '1:337862523976:ios:af056e034cf5ce73d4ec7d',
    messagingSenderId: '337862523976',
    projectId: 'mush-on',
    storageBucket: 'mush-on.firebasestorage.app',
    iosBundleId: 'com.stefanominiconsulting.mushOn',
  );
}
